# Generated by Django 4.1.7 on 2023-04-03 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ideas", "0002_alter_idea_presenter"),
    ]

    operations = [
        migrations.AddField(
            model_name="presenter",
            name="game",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ideas.game",
            ),
        ),
    ]
