# Generated by Django 4.1.7 on 2023-04-03 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ideas", "0003_presenter_game"),
    ]

    operations = [
        migrations.AlterField(
            model_name="idea",
            name="presenter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="ideas.presenter",
            ),
        ),
    ]
