# Generated by Django 4.1.7 on 2023-04-03 21:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ideas", "0004_alter_idea_presenter"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vote",
            name="presenter",
        ),
    ]
